### ISSUE TITLE
Service is not exposing 

### ISSUE THREAD

**Issue by dshamanthreddy** [luizkowalski/microservices-netflix-sample#2]
I try to follow the steps you mention but I was doing it on AWS servers , I have exposed the service but can't see my External IP Address

**Comment by luizkowalski** [comment]
I have never deployed on AWS directly, I've always used container orchestrators like Rancher or Kubernetes...
Does your machine has a public ip? are you opening the ports necessary to run the application on the VPC?
If you want, I can try help you, but I'm gonna need more information

**Comment by dshamanthreddy** [comment]
@luizkowalski  thanks , yeah I do have Public IP and my vpc is open. In my case I installed kubernetes with kubeadm on Aws Ec2 . I have one master and two nodes.

**Comment by dshamanthreddy** [comment]
hey @luizkowalski  I have eureka up  and running , Deployed hystrix also and exposed it on nodeport , but it not registering with eureka

**Comment by luizkowalski** [comment]
can you ssh into your hystrix server and see if it can ping your eureka server?

**Comment by dshamanthreddy** [comment]
it says bad address when trying to ping eureka server

**Comment by luizkowalski** [comment]
There you have it...your EC2 instances can't see each other.

**Comment by dshamanthreddy** [comment]
Thanks for the response. I have changed localhost to EC2 dns name, it worked  !!But I have few questions:
1.I cannot access the eureka on port 8761, but can only access it on Nodeport 
2. why to pass eureka client defaultZone twice in bootstrap.yml file. I mean its already hardcoded  and also passing through environment variable {EUREKA_URL}

**Comment by luizkowalski** [comment]
> 1.I cannot access the eureka on port 8761, but can only access it on Nodeport

that depends on how you've mapped the ports on the server

> 2. why to pass eureka client defaultZone twice in bootstrap.yml file.

there are configurations for different profiles there...locally, I run on localhost, but on production, I want to specify the URL. See [this](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-profiles.html)
