### ISSUE TITLE
How does Kubernetes know how to put services in OUT_OF_SERVICE state?

### ISSUE THREAD

**Issue by angheladrianclaudiu** [luizkowalski/microservices-netflix-sample#3]
If you are using Eureka on a Kubernetes cluster, how does it know to put the current version of a service on OUT_OF_SERVICE when deploying a new version of that service?

**Comment by luizkowalski** [comment]
usually through [Liveness and Readiness Probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/) configuration, but you have to use YAML file to define it

**Comment by angheladrianclaudiu** [comment]
Well, I would really want to see this kind of configuration up and running. The example you have here I am pretty sure it will short circuit the routes in Zuul if used on live environment on Kubernetes. So do you happen to have a liveness and readiness probes configuration for Eureka register/deregister services?

**Comment by luizkowalski** [comment]
>  The example you have here I am pretty sure it will short circuit the routes in Zuul if used on live environment on Kubernetes

what do you mean? why would that happen?

**Comment by angheladrianclaudiu** [comment]
I am trying to understand what would happen in the following situation:

I have 3 instances for contacts microservice. If I scale down to 2 instances or if I kill one of them, how would Eureka behave in this scenario? Will the instance be removed from the registry or will it cause problems to Zuul?

**Comment by luizkowalski** [comment]
I see now. well, let me do some tests and I can give you a proper answer soon :)

**Comment by luizkowalski** [comment]
to try and see what is happening, I came with this: 
first, I set up Eureka and run two contacts service instance:

![screen shot 2018-07-14 at 5 28 53 pm](https://user-images.githubusercontent.com/112706/42725861-6e30936c-878b-11e8-85a7-8a24dfc7b602.png)

Then, I set up a new endpoint on contacts, to print the running port:

```java
@Value("${PORT}")
String port;

@RequestMapping(method = RequestMethod.GET, path = "/")
    public String getInformation() throws Exception
    {
        return port;
    }
````

then, I called this new endpoint through Zull:

```
# luizkowalski at lzk in ~/java_dev/contacts on git:master ✖︎ [17:40:58]
→ curl 127.0.0.1:8080/contacts
8082%
# luizkowalski at lzk in ~/java_dev/contacts on git:master ✖︎ [17:41:02]
→ curl 127.0.0.1:8080/contacts
8081%
# luizkowalski at lzk in ~/java_dev/contacts on git:master ✖︎ [17:41:03]
→ curl 127.0.0.1:8080/contacts
8082%
# luizkowalski at lzk in ~/java_dev/contacts on git:master ✖︎ [17:41:04]
→ curl 127.0.0.1:8080/contacts
8081%
``` 

As you see, the requests are being load balance on Zuul. Then, I killed one of the server (8082) and imediately, did more requests:

```
# luizkowalski at lzk in ~/java_dev/contacts on git:master ✖︎ [17:42:49]
→ curl 127.0.0.1:8080/contacts
8081%
# luizkowalski at lzk in ~/java_dev/contacts on git:master ✖︎ [17:43:04]
→ curl 127.0.0.1:8080/contacts
8081%
# luizkowalski at lzk in ~/java_dev/contacts on git:master ✖︎ [17:43:05]
→ curl 127.0.0.1:8080/contacts
8081%
# luizkowalski at lzk in ~/java_dev/contacts on git:master ✖︎ [17:43:05]
→ curl 127.0.0.1:8080/contacts
8081%
# luizkowalski at lzk in ~/java_dev/contacts on git:master ✖︎ [17:43:06]
→ curl 127.0.0.1:8080/contacts
8081%
# luizkowalski at lzk in ~/java_dev/contacts on git:master ✖︎ [17:43:07]
→ curl 127.0.0.1:8080/contacts
8081%
# luizkowalski at lzk in ~/java_dev/contacts on git:master ✖︎ [17:43:07]
```
That happened because when I stopped the service on 8082, you can see the log output:

```
^C2018-07-14 17:43:03.653  INFO 4164 --- [       Thread-9] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@29d0ffd0: startup date [Sat Jul 14 17:39:12 CEST 2018]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@66ed9578
2018-07-14 17:43:03.663  INFO 4164 --- [       Thread-9] o.s.c.n.e.s.EurekaServiceRegistry        : Unregistering application contacts-service with eureka with status DOWN
2018-07-14 17:43:03.664  WARN 4164 --- [       Thread-9] com.netflix.discovery.DiscoveryClient    : Saw local status change event StatusChangeEvent [timestamp=1531582983664, current=DOWN, previous=UP]
2018-07-14 17:43:03.666  INFO 4164 --- [       Thread-9] com.netflix.discovery.DiscoveryClient    : Shutting down DiscoveryClient ...
2018-07-14 17:43:03.667  INFO 4164 --- [       Thread-9] com.netflix.discovery.DiscoveryClient    : Unregistering ...
2018-07-14 17:43:03.692  INFO 4164 --- [       Thread-9] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_CONTACTS-SERVICE/192.168.178.20:contacts-service:8082 - deregister  status: 200
```

Right after the shutdow, the service pinged Eureka and let Eureka know that it was going down and couldn't serve any more requests. Since Zuul only cares about services registered with **UP** status, this service was unavailabe for load balancing. 

Then you asked:
>  how would Eureka behave in this scenario?

generaly speaking, there is no "behavior" from Eureka, it is just a "database for services", so if the service says it is down, Eureka removes it

![screen shot 2018-07-14 at 5 45 29 pm](https://user-images.githubusercontent.com/112706/42726014-d8de7330-878d-11e8-9d66-7956b8049288.png)

and since it is removed (e.g. registered as **DOWN**), Zuul can't see nor balance requests to it. You can keep this exact same behaviour on Kubernetes if you deploy all these services on it

**Comment by angheladrianclaudiu** [comment]
Great. Thank you for the detailed answer. One more question arises though: but what if the instance that you are shutting down is having some requests that is treating right in that moment?
Wouldn't it be better to first put it out of service somehow, and then shut it down? 

I am talking about calling `PUT /eureka/v2/apps/appID/instanceID/status?value=OUT_OF_SERVICE` first and then taking it down in 2-3 minutes.

See here: https://github.com/Netflix/eureka/wiki/Eureka-REST-operations

**Comment by luizkowalski** [comment]
I don't think this is necessary if you do a [graceful shutdown](https://github.com/SchweizerischeBundesbahnen/springboot-graceful-shutdown/blob/master/src/main/java/ch/sbb/esta/openshift/gracefullshutdown/GracefulShutdownHook.java).

During the graceful shutdown, the app will finish the requests, stop accepting new one, set its state to OUT_OF_SERVICE and then shutdown.

Also, check the `/shutdown` endpoint

**Comment by angheladrianclaudiu** [comment]
Nice project. Thank you for the link. I will try it out and give you some feedback about it.

Another question: what do you think about [Spring Cloud Kubernetes](https://github.com/spring-cloud-incubator/spring-cloud-kubernetes) project?
I am trying to integrate it into our project in order to use [Discovery Client for Kubernetes](https://github.com/spring-cloud-incubator/spring-cloud-kubernetes#discoveryclient-for-kubernetes), but when I am trying to integrate it with Zuul I encountered this: https://github.com/spring-cloud-incubator/spring-cloud-kubernetes/issues/216

I put up a sample project that reproduces the issue on our cluster since I can't put our code out on Github: https://github.com/angheladrianclaudiu/zuul-kubernetes

Cheers,
Adrian

**Comment by luizkowalski** [comment]
really interesting, but I've never worked with this project so I can't help here
